### ISSUE TITLE
Create a demo project for common criteria collection

### ISSUE THREAD

**Issue by RanabirChakraborty** [ansible-middleware/common_criteria#9]
Right now we don't have a demo for the common_criteria collection. Just like other ansible-middleware collections we need to have one for this project.

**Comment by rpelisse** [comment]
We are actually missing demo for a few other collection, but yes, one for CC on both Wildfly and JWS would be nice. Are you up for the task?

**Comment by RanabirChakraborty** [comment]
Thanks, @rpelisse for assigning me the task.

**Comment by rpelisse** [comment]
Thanks for volunteering!

**Comment by RanabirChakraborty** [comment]
Now you can find [common_criteria_demo](https://github.com/ansible-middleware/common_criteria_demo) inside Ansible Middleware.
